version: '3'

volumes:
  db:

services:

  db:
    build: ./database
    container_name: db
    restart: always
    env_file: 
      - .env

  fastapi:
    build: ./src
    container_name: fastapi
    restart: always
    env_file: 
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80 
    depends_on:
      - fastapi
    container_name: nginx
